version: '3.1'
services:

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=user1
      - POSTGRES_PASSWORD=iamroot
      #- TZ=Europe/Moscow

  server:
    build: server
    image: server-image
    container_name: server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats
      - SPRING_DRIVER_CLASS_NAME:org.postgresql.Driver
      - SPRING_DATASOURCE_USERNAME:user1
      - SPRING_DATASOURCE_PASSWORD:iamroot
      #- TZ=Europe/Moscow

#  ewm-service:
#    ports:
#      - "8080:8080"

#  ewm-db:
#    image: postgres:14-alpine
