DROP TABLE IF EXISTS hits CASCADE;

CREATE TABLE if not exists hits (
  id integer generated by default as identity not null PRIMARY KEY,
  app varchar(30) not null,
  uri varchar not null,
  ip varchar(15) not null,
  ts TIMESTAMP WITHOUT TIME ZONE not null
);
